name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.5'
          - '2.6'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: ${{ matrix.ruby != '2.6' }}
      - name: Bundle install (Ruby 2.6)
        if: matrix.ruby == '2.6'
        run: bundle install --jobs 4
      - name: Run the default task
        run: bundle exec rake
